#!/bin/bash

FLAGS=--encrypt-key=8257025A
SRC=/srv
DEST=scp://admin@agrippa.local/mnt/HD/HD_a2/Backup/ashley

mail_from=`whoami`@`hostname`
mail_rcpt=`whoami`@`hostname`

export PASSPHRASE=

timestamp(){
  date +%s
}

notice(){
  sendmail -t <<EOF
From: $mail_from
To: $mail_rcpt
Date: $(date)
Subject: $1

$2
EOF
}

statedir=/srv/backup
mkdir -p $statedir
cd $statedir

hour=3600
day=$((hour*24))

now=$(timestamp)
partial_date=$(cat $statedir/last-partial 2>/dev/null)
partial_age=$((now-partial_date))

min_partial_age=$day
max_partial_age=$((day*3))

. $(cd "`dirname "$0"`"; pwd)/config

if [[ $partial_age -lt $min_partial_age ]]; then

  echo "Last backup too recent"
  notice "Last backup too recent" "test"

else

  echo "Backup in progress"

  if out="$(duplicity $FLAGS $SRC $DEST 2>&1)"; then
    timestamp > $statedir/last-partial
    notice "Backup OK" "$out"
  elif [[ $partial_age -gt $max_partial_age ]]; then
    notice "Backup could not proceed" "$out"
    echo "Too long since last backup"
  fi

fi

#if duplicity full $FLAGS $SRC $DEST; then
#  timestamp > $statedir/last-partial
#  timestamp > $statedir/last-full
#fi

